              call synchro_omp_scater(param_int, ithread_io,
     &                          lth, sens,lgo,lwait,Nbre_socket,
     &                          Nbre_thread_actif,thread_parsock,
     &                          lok_shap_sock, lok_shap,neq_lok,
     &                          socket , socket_topology, socket_pos,
     &                          ithread, thread_topology,thread_pos_tmp,
     &                          synchro_receive_sock, synchro_send_sock,
     &                          synchro_receive_th  , synchro_send_th,
     &                          ibloc , jbloc , kbloc , ijkv_thread,
     &                          icache, jcache, kcache, ijkv_sdm,
     &                          ind_dm_omp,
     &                          drodm, coe, xmut,
     &                          lok(1),lok(ipt_lok_sock),
     &                          lok(ipt_lok), omp_go )
