                drodm(l , 1) = drodm(l ,1)       + flu1
                drodm(l0, 1) = drodm(l0,1)       - flu1
                drodm(l , 2) = drodm(l ,2)       + flu2
                drodm(l0, 2) = drodm(l0,2)       - flu2
                drodm(l , 3) = drodm(l ,3)       + flu3
                drodm(l0, 3) = drodm(l0,3)       - flu3
                drodm(l , 4) = drodm(l ,4)       + flu4
                drodm(l0, 4) = drodm(l0,4)       - flu4
                drodm(l , 5) = drodm(l ,5)       + flu5
                drodm(l0, 5) = drodm(l0,5)       - flu5
                drodm(l , 6) = drodm(l ,6)       + flu6
                drodm(l0, 6) = drodm(l0,6)       - flu6
