#! /bin/sh
#
# Installation du module FastStrand
# Par defaut dans : $CASSIOPEE/Dist/bin/$ELSAPROD/
# Sinon : dans le repertoire specifie en argument
#
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in you environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit 1
    fi
    if [ "$ELSAPROD" = "" ]; then
        export ELSAPROD=x86_r8
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo ' -or-'
    echo 'install <dir>: install in directory <dir>.'
    exit 1
fi

# if specific python exe name
if [ "$PYTHONEXE" != "" ]; then
    alias python=$PYTHONEXE
fi

# set production mode (0: scons+setup, 1: scons+pip, 2: setup legacy)
if [ "$PRODMODE" = "" ]; then
    PRODMODE=0
fi

# Compilation et installation
sconsf=`which scons`
which scons &>/dev/null
if [ $? -eq 0 ]; then
    if [ "$OMP_NUM_THREADS" != "" ]; then
        export SCONSOPT="-j $OMP_NUM_THREADS"
    else
        export SCONSOPT=""
    fi
    python $sconsf install prefix="$INSTALLPATH" "$SCONSOPT"
    [ $? != 0 ] && exit 1;
    #touch FastStrand/fastStrand.cpp
    rm -f build/lib.*/FastStrand/faststrand.*
    rm -f build/lib.*/FastStrand/faststrand-*.*
    if [ $PRODMODE -eq 0 ]; then
        python setup.py install --prefix="$INSTALLPATH"
        [ $? != 0 ] && exit 1;
    elif [ $PRODMODE -eq 1 ]; then
        python -m pip install  --no-cache-dir --no-binary=FastStrand --ignore-installed --upgrade --prefix="$INSTALLPATH" .
        [ $? != 0 ] && exit 1;
    elif [ $PRODMODE -eq 2 ]; then
        python -m pip install --ignore-installed --upgrade --prefix="$INSTALLPATH" .
        [ $? != 0 ] && exit 1;    
    fi
else
    python setupLegacy.py install --prefix="$INSTALLPATH"
    [ $? != 0 ] && exit 1;
fi

# Install libfast
#python installLib.py

# Test installation
python test/t1.py
