#! /bin/sh
echo 'Installing Fast tests and doc'
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

if ([ $# -eq 0 ])
then
    PRODUCTION=0
    # Destination docs
    DEST="./doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Fast"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 2 ])
then
    PRODUCTION=1
    # Destination docs
    DEST="../../../web/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Fast"
    # Destination des release notes
    DEST3="../../../web/Download"
else
    echo 'install: install locally'
    echo 'install 1 2: install in web/doc.'
    exit
fi

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi

    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s ../test Examples/Fast
fi
cd ..

# Build html
touch source/*.rst
sphinx-build -b html ./source ./build
if ([ $PRODUCTION -eq 1 ])
then
# Build pdf
    sphinx-build -b latex ./source ./build
    cd build
    pdflatex Fast >& /dev/null
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    sed -i 's/Fast.Fast/Fast/g' build/Fast.html
    cp build/Fast.html $DEST
    cp build/Fast.pdf $DEST
    cp -rf source/documents $DEST/
    # ajoute le search index
    cp build/searchindex.js $DEST
    cp build/genindex.html $DEST
    cp build/py-modindex.html $DEST
    cp build/search.html $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../Fast/Fast.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='Fast-'$version1'.txt'
    cp Fast.txt $DEST3/$v
fi
