#! /bin/sh
echo 'Installing FastC tests and doc'
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

PRODUCTION=1
# Destination docs
DEST="../../../docs/doc"
# Destination tests unitaires
DEST2="$DEST/Examples/FastC"
# Destination des release notes
DEST3="../../../docs/Download"

# Copy all docs locally
cp ../../FastS/doc/source/FastS.rst source/
cp ../../Fast/doc/source/Fast.rst source/

# Build html
touch source/*.rst
sphinx-build -b html ./source ./build

# modif de search index
FILE=build/searchindex.js
sed -i 's/FastS\.FastS/FastS/g' $FILE
sed -i 's/Fast\.Fast/Fast/g' $FILE

# meme modif de genindex
FILE=build/genindex.html
sed -i 's/FastS\.FastS/FastS/g' $FILE
sed -i 's/Fast\.Fast/Fast/g' $FILE

cp build/searchindex.js $DEST
cp build/genindex.html $DEST
cp build/py-modindex.html $DEST
cp build/search.html $DEST
