C ** Warning: this file is auto-generated from corr_fluausm_select.for
C ** Do not edit this file!

c***********************************************************************
      subroutine corr_fluausm_select(ndom, ithread, idir, bctype,
     &                        size_flux, iflow,
     &                        param_int, param_real,
     &                        ind_loop, inc_bc,
     &                        rop, drodm  , wig, flux,
     &                        venti, ventj, ventk,
     &                        ti,tj,tk,vol, xmut)
c***********************************************************************
c_U   USER : PECHIER
c
c     ACT
c_A    Appel du calcul des flux explicites
c
c     VAL
c_V    gaz parfait monoespece
c_V    processeur domaine
c_V    steady/unsteady
c
c     INP
c_I    tijk     : vecteur normale aux facettes des mailles
c_I    ventijk     : vitesses d entrainement aux facettes preced.
c_I    qm,qp    : etats droit et gauche aux interfaces d une maille
c
c     LOC
c_L    flu      : flux convectifs dans une direction de maillage
c
c     I/O
c_/    drodm    : increment de la solution
c***********************************************************************
      implicit none

#include "FastS/param_solver.h"

      INTEGER_E ndom, ithread, idir, iflow, ind_loop(6), param_int(0:*)
      INTEGER_E bctype, size_flux , inc_bc(3)


      REAL_E rop(*),drodm(*), ti(*),tj(*),tk(*),vol(*),
     & venti(*),ventj(*),ventk(*), wig(*), xmut(*), flux(*)

      REAL_E param_real(0:*)

C Var loc
      INTEGER_E option, ale

      if(ind_loop(1).gt.ind_loop(2)) return 
      if(ind_loop(3).gt.ind_loop(4)) return 
      if(ind_loop(5).gt.ind_loop(6)) return

      ale = min(param_int(LALE),1)

       option =1000*ale
     &        + 100*param_int(SLOPE)
     &        +  10*iflow
     &        +      param_int(ITYPZONE)

       IF  (option.eq.220) THEN
                                               
         call corr_fluausm_lamin_o3_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.221) THEN
                                               
         call corr_fluausm_lamin_o3_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.222) THEN
                                               
         call corr_fluausm_lamin_o3_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.223) THEN
                                               
         call corr_fluausm_lamin_o3_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.620) THEN
                                               
         call corr_fluausm_lamin_o3sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.621) THEN
                                               
         call corr_fluausm_lamin_o3sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.622) THEN
                                               
         call corr_fluausm_lamin_o3sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.623) THEN
                                               
         call corr_fluausm_lamin_o3sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.520) THEN
                                               
         call corr_fluausm_lamin_o5_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.521) THEN
                                               
         call corr_fluausm_lamin_o5_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.522) THEN
                                               
         call corr_fluausm_lamin_o5_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.523) THEN
                                               
         call corr_fluausm_lamin_o5_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.720) THEN
                                               
         call corr_fluausm_lamin_o5sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.721) THEN
                                               
         call corr_fluausm_lamin_o5sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.722) THEN
                                               
         call corr_fluausm_lamin_o5sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.723) THEN
                                               
         call corr_fluausm_lamin_o5sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.230) THEN
                                               
         call corr_fluausm_SA_o3_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.231) THEN
                                               
         call corr_fluausm_SA_o3_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.232) THEN
                                               
         call corr_fluausm_SA_o3_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.233) THEN
                                               
         call corr_fluausm_SA_o3_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.630) THEN
                                               
         call corr_fluausm_SA_o3sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.631) THEN
                                               
         call corr_fluausm_SA_o3sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.632) THEN
                                               
         call corr_fluausm_SA_o3sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.633) THEN
                                               
         call corr_fluausm_SA_o3sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.530) THEN
                                               
         call corr_fluausm_SA_o5_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.531) THEN
                                               
         call corr_fluausm_SA_o5_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.532) THEN
                                               
         call corr_fluausm_SA_o5_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.533) THEN
                                               
         call corr_fluausm_SA_o5_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.730) THEN
                                               
         call corr_fluausm_SA_o5sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.731) THEN
                                               
         call corr_fluausm_SA_o5sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.732) THEN
                                               
         call corr_fluausm_SA_o5sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.733) THEN
                                               
         call corr_fluausm_SA_o5sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.210) THEN
                                               
         call corr_fluausm_euler_o3_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.211) THEN
                                               
         call corr_fluausm_euler_o3_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.212) THEN
                                               
         call corr_fluausm_euler_o3_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.213) THEN
                                               
         call corr_fluausm_euler_o3_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.610) THEN
                                               
         call corr_fluausm_euler_o3sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.611) THEN
                                               
         call corr_fluausm_euler_o3sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.612) THEN
                                               
         call corr_fluausm_euler_o3sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.613) THEN
                                               
         call corr_fluausm_euler_o3sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.510) THEN
                                               
         call corr_fluausm_euler_o5_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.511) THEN
                                               
         call corr_fluausm_euler_o5_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.512) THEN
                                               
         call corr_fluausm_euler_o5_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.513) THEN
                                               
         call corr_fluausm_euler_o5_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.710) THEN
                                               
         call corr_fluausm_euler_o5sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.711) THEN
                                               
         call corr_fluausm_euler_o5sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.712) THEN
                                               
         call corr_fluausm_euler_o5sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.713) THEN
                                               
         call corr_fluausm_euler_o5sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1220) THEN
                                               
         call corr_fluausm_ale_lamin_o3_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1221) THEN
                                               
         call corr_fluausm_ale_lamin_o3_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1222) THEN
                                               
         call corr_fluausm_ale_lamin_o3_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1223) THEN
                                               
         call corr_fluausm_ale_lamin_o3_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1620) THEN
                                               
         call corr_fluausm_ale_lamin_o3sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1621) THEN
                                               
         call corr_fluausm_ale_lamin_o3sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1622) THEN
                                               
         call corr_fluausm_ale_lamin_o3sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1623) THEN
                                               
         call corr_fluausm_ale_lamin_o3sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1520) THEN
                                               
         call corr_fluausm_ale_lamin_o5_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1521) THEN
                                               
         call corr_fluausm_ale_lamin_o5_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1522) THEN
                                               
         call corr_fluausm_ale_lamin_o5_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1523) THEN
                                               
         call corr_fluausm_ale_lamin_o5_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1720) THEN
                                               
         call corr_fluausm_ale_lamin_o5sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1721) THEN
                                               
         call corr_fluausm_ale_lamin_o5sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1722) THEN
                                               
         call corr_fluausm_ale_lamin_o5sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1723) THEN
                                               
         call corr_fluausm_ale_lamin_o5sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1230) THEN
                                               
         call corr_fluausm_ale_SA_o3_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1231) THEN
                                               
         call corr_fluausm_ale_SA_o3_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1232) THEN
                                               
         call corr_fluausm_ale_SA_o3_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1233) THEN
                                               
         call corr_fluausm_ale_SA_o3_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1630) THEN
                                               
         call corr_fluausm_ale_SA_o3sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1631) THEN
                                               
         call corr_fluausm_ale_SA_o3sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1632) THEN
                                               
         call corr_fluausm_ale_SA_o3sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1633) THEN
                                               
         call corr_fluausm_ale_SA_o3sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1530) THEN
                                               
         call corr_fluausm_ale_SA_o5_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1531) THEN
                                               
         call corr_fluausm_ale_SA_o5_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1532) THEN
                                               
         call corr_fluausm_ale_SA_o5_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1533) THEN
                                               
         call corr_fluausm_ale_SA_o5_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1730) THEN
                                               
         call corr_fluausm_ale_SA_o5sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1731) THEN
                                               
         call corr_fluausm_ale_SA_o5sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1732) THEN
                                               
         call corr_fluausm_ale_SA_o5sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1733) THEN
                                               
         call corr_fluausm_ale_SA_o5sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1210) THEN
                                               
         call corr_fluausm_ale_euler_o3_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1211) THEN
                                               
         call corr_fluausm_ale_euler_o3_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1212) THEN
                                               
         call corr_fluausm_ale_euler_o3_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1213) THEN
                                               
         call corr_fluausm_ale_euler_o3_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1610) THEN
                                               
         call corr_fluausm_ale_euler_o3sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1611) THEN
                                               
         call corr_fluausm_ale_euler_o3sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1612) THEN
                                               
         call corr_fluausm_ale_euler_o3sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1613) THEN
                                               
         call corr_fluausm_ale_euler_o3sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1510) THEN
                                               
         call corr_fluausm_ale_euler_o5_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1511) THEN
                                               
         call corr_fluausm_ale_euler_o5_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1512) THEN
                                               
         call corr_fluausm_ale_euler_o5_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1513) THEN
                                               
         call corr_fluausm_ale_euler_o5_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1710) THEN
                                               
         call corr_fluausm_ale_euler_o5sc_3dfull(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1711) THEN
                                               
         call corr_fluausm_ale_euler_o5sc_3dhomo(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1712) THEN
                                               
         call corr_fluausm_ale_euler_o5sc_3dcart(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
       ELSEIF (option.eq.1713) THEN
                                               
         call corr_fluausm_ale_euler_o5sc_2d(ndom,
     &                 ithread, idir,bctype, size_flux,
     &                 param_int, param_real,
     &                 ind_loop, inc_bc,
     &                 rop, drodm , wig, flux,
     &                 venti, ventj, ventk,
     &                 ti, tj, tk, vol, xmut)
                                               
      ELSE
         write(*,*) ' option = ' , option 
            write(*,*)'Unknown flux options'
           call error('correction_flu$',70,1)

      ENDIF
 
      end
