C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.13 (r6666M) -  1 Mar 2018 15:30
C
C  Differentiation of core3gmres in forward (tangent) mode:
C   variations   of useful results: drodm
C   with respect to varying inputs: drodm
      SUBROUTINE core3as2_kry_d(param_int, ind_loop, drodm, drodmd, coe)
      IMPLICIT NONE
C
C
C
      INTEGER*4 param_int(0:*), ind_loop(6)
      REAL*8 drodm(param_int(41), param_int(36))
      REAL*8 drodmd(param_int(41), param_int(36))
      REAL*8 coe(param_int(41), param_int(39))
C
      INTEGER*4 l, i, j, k, lij
C
C    adresse point courant pour tableau de la taille d'un domaine 
      INTEGER*4 inddm, i_1, j_1, k_1
C
      IF (param_int(36) .EQ. 6) THEN
        DO k=ind_loop(5),ind_loop(6)
          DO j=ind_loop(3),ind_loop(4)
            lij = 1 + (ind_loop(1)+param_int(0+3)-1) + (j+param_int(0+3)
     +        -1)*param_int(0) + (k+param_int(0+4)-1)*param_int(0)*
     +        param_int(0+1)
CDIR$ IVDEP
            DO l=lij,lij+ind_loop(2)-ind_loop(1)
              drodmd(l, 1) = coe(l, 1)*drodmd(l, 1)
              drodmd(l, 2) = coe(l, 1)*drodmd(l, 2)
              drodmd(l, 3) = coe(l, 1)*drodmd(l, 3)
              drodmd(l, 4) = coe(l, 1)*drodmd(l, 4)
              drodmd(l, 5) = coe(l, 1)*drodmd(l, 5)
              drodmd(l, 6) = coe(l, 1)*drodmd(l, 6)*1.e0
            ENDDO
          ENDDO
        ENDDO
      ELSE
        DO k=ind_loop(5),ind_loop(6)
          DO j=ind_loop(3),ind_loop(4)
            lij = 1 + (ind_loop(1)+param_int(0+3)-1) + (j+param_int(0+3)
     +        -1)*param_int(0) + (k+param_int(0+4)-1)*param_int(0)*
     +        param_int(0+1)
CDIR$ IVDEP
            DO l=lij,lij+ind_loop(2)-ind_loop(1)
              drodmd(l,1) = coe(l, 1)*drodmd(l, 1)
              drodmd(l,2) = coe(l, 1)*drodmd(l, 2)
              drodmd(l,3) = coe(l, 1)*drodmd(l, 3)
              drodmd(l,4) = coe(l, 1)*drodmd(l, 4)
              drodmd(l,5) = coe(l, 1)*drodmd(l, 5)
            ENDDO
          ENDDO
        ENDDO
      END IF
      END
