# Variables for LBM
lbm_one_3      = 1./3.;
lbm_one_9      = 1./9.;
lbm_two_9      = 2./9.;
lbm_four_9     = 4./9.;
lbm_one_18     = 1./18.;
lbm_eight_27   = 8./27.;
lbm_two_27     = 2./27.;
lbm_one_36     = 1./36.;
lbm_one_54     = 1./54.;
lbm_one_72     = 1./72.;
lbm_one_216    = 1./216.;

NIJK                        = 0
IJKV                        =20 
NEQ_LBM                     =86
PT_LBM_Cs                   =90  
PT_LBM_Ws                   =91 
LBM_COL_OP                  =92 
PT_LBM_Cminus               =93 
PT_LBM_BC                   =94 
LBM_NQ_BC                   =95 
PT_LBM_H2H3                 =96 
PT_LBM_SPEC                 =97 
LBM_FILTER                  =98 
PT_LBM_FILTER_WGHT          =99 
LBM_FILTER_SZ               =100 
PT_LBM_FILTER_STNCL         =101 
LBM_SPONGE                  =102 
LBM_SPONGE_SIZE             =103 
LBM_SPONGE_PREP             =104 
flag_streaming              =105
flag_macro                  =106
flag_collision_operator     =107
flag_collision              =108
LBM_isforce                 =109
LBM_BConQstar               =110
flag_BConQstar_switch       =111
LBM_IBC                     =112
LBM_IBC_NUM                 =113
PT_LBM_IBC_LIST             =114
PT_LBM_IBC_DIST             =115
PT_LBM_IBC_DIR              =116
LBM_IBC_PREP                =117
LBM_IBC_CONNECTOR           =118
LBM_spng_xmin               =119
LBM_spng_xmax               =120 
LBM_spng_ymin               =121
LBM_spng_ymax               =122 
LBM_spng_zmin               =123
LBM_spng_zmax               =124

IBC_PT_FLUX                 =125

LBM_c0                      =42
LBM_taug                    =43
LBM_difcoef                 =44
LBM_filter_sigma            =45
LBM_forcex                  =46
LBM_adaptive_filter_chi     =49
LBM_chi_spongetypeII        =50
LBM_HRR_sigma               =51
LBM_gamma_precon            =52
LBM_zlim                    =53
