        tix  = ti(lt          +v1mtr)
        tiy  = ti(lt          +v2mtr)
        tiz  = ti(lt          +v3mtr)
        tix1 = ti(lt+inci_mtr +v1mtr)
        tiy1 = ti(lt+inci_mtr +v2mtr)
        tiz1 = ti(lt+inci_mtr +v3mtr)

        tjx  = tj(lt          +v1mtr)
        tjy  = tj(lt          +v2mtr)
        tjz  = tj(lt          +v3mtr)
        tjx1 = tj(lt+incj_mtr +v1mtr)
        tjy1 = tj(lt+incj_mtr +v2mtr)
        tjz1 = tj(lt+incj_mtr +v3mtr)

        tkx  = tk(lt          +v1mtr)
        tky  = tk(lt          +v2mtr)
        tkz  = tk(lt          +v3mtr)
        tkx1 = tk(lt+inck_mtr +v1mtr)
        tky1 = tk(lt+inck_mtr +v2mtr)
        tkz1 = tk(lt+inck_mtr +v3mtr)
