C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.13 (r6666M) -  1 Mar 2018 15:30
C
C  Differentiation of corr_fluroe_select in forward (tangent) mode:
C   variations   of useful results: drodm
C   with respect to varying inputs: rop drodm
      SUBROUTINE CORR_FLUROE_SELECT_D(ndom, ithread, idir, param_int, 
     +                                param_real, ind_loop, rop, ropd, 
     +                                drodm, drodmd, wig, venti, ventj, 
     +                                ventk, ti, tj, tk, vol, xmut)
      IMPLICIT NONE
C
      INTEGER*4 ndom, ithread, idir, ind_loop(6), param_int(0:*)
C
C
      REAL*8 rop(*), xmut(*), drodm(*), ti(*), tj(*), tk(*), vol(*), 
     +       venti(*), ventj(*), ventk(*), wig(*)
      REAL*8 ropd(*), drodmd(*)
C
      REAL*8 param_real(0:*)
C
C Var loc
      INTEGER*4 option, iflow_loc
      EXTERNAL ERROR
C
      IF (ind_loop(1) .GT. ind_loop(2)) THEN
        RETURN
      ELSE IF (ind_loop(3) .GT. ind_loop(4)) THEN
        RETURN
      ELSE IF (ind_loop(5) .GT. ind_loop(6)) THEN
        RETURN
      ELSE
C
        iflow_loc = param_int(27)
        IF (iflow_loc .EQ. 2) iflow_loc = 1
C
        option = 1000*param_int(34) + 100*param_int(64) + 10*iflow_loc +
     +    param_int(25)
C
        IF (option .EQ. 213) THEN
          CALL CORR_FLUROE_EULER_O3_2D_D(ndom, ithread, idir, param_int
     +                                   , param_real, ind_loop, rop, 
     +                                   ropd, drodm, drodmd, wig, venti
     +                                   , ventj, ventk, ti, tj, tk, vol
     +                                   , xmut)
C
        ELSE
          WRITE(*, *) ' option = ', option
          WRITE(*, *) 'Unknown flux options'
          CALL ERROR('correction_flu$', 70, 1)
C
        END IF
      END IF
      END
