C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.13 (r6666M) -  1 Mar 2018 15:30
C
C  Differentiation of fluroe_select in forward (tangent) mode:
C   variations   of useful results: drodm
C   with respect to varying inputs: rop drodm
      SUBROUTINE FLUROE_SELECT_D(ndom, nitcfg, ithread, nptpsi, 
     +                           param_int, param_real, ind_dm, ind_loop
     +                           , ijkv_thread, ijkv_sdm, 
     +                           synchro_send_sock, synchro_send_th, 
     +                           synchro_receive_sock, 
     +                           synchro_receive_th, ibloc, jbloc, kbloc
     +                           , icache, jcache, kcache, psi, wig, 
     +                           stat_wig, rop, ropd, drodm, drodmd, ti
     +                           , ti_df, tj, tj_df, tk, tk_df, vol, 
     +                           vol_df, venti, ventj, ventk, xmut)
      IMPLICIT NONE
C
      INTEGER*4 ndom, nitcfg, ithread, nptpsi, icache, jcache, kcache, 
     +          ibloc, jbloc, kbloc, ijkv_thread(3), ijkv_sdm(3), 
     +          ind_loop(6), ind_dm(6), synchro_send_sock(3), 
     +          synchro_send_th(3), synchro_receive_sock(3), 
     +          synchro_receive_th(3), param_int(0:*)
C
      REAL*8 rop(*), xmut(*), drodm(*), ti(*), tj(*), tk(*), vol(*), 
     +       venti(*), ventj(*), ventk(*), wig(*), stat_wig(*), ti_df(*)
     +       , tj_df(*), tk_df(*), vol_df(*)
      REAL*8 ropd(*), drodmd(*)
C
C$$$      REAL*8 xmut(*), ti(*),tj(*),tk(*),vol(*),
C$$$     & venti(*),ventj(*),ventk(*), wig(*),stat_wig(*),
C$$$     & ti_df(*),tj_df(*),tk_df(*),vol_df(*)
C
      REAL*8 param_real(0:*)
CZONE TEST
      REAL*8 psi(nptpsi)
C$$$      REAL*8 drodm(param_int(36) * param_int(41))
C$$$      REAL*8 rop(param_int(36) * param_int(41))
C$$$      REAL*8 drodmd(param_int(36) * param_int(41))
C$$$      REAL*8 drodmtmp(param_int(36) * param_int(41))
C$$$      REAL*8 roptmp(param_int(36) * param_int(41))
C$$$      REAL*8 ropd(param_int(36) * param_int(41))
C$$$      REAL*8 erreur(param_int(36) * param_int(41))
C$$$      REAL*8 epsilon, tmp
C$$$      INTEGER*4 i
C
C Var loc
      INTEGER*4 option
      EXTERNAL ERROR
C
      IF (ind_loop(1) .GT. ind_loop(2)) THEN
        RETURN
      ELSE IF (ind_loop(3) .GT. ind_loop(4)) THEN
        RETURN
      ELSE IF (ind_loop(5) .GT. ind_loop(6)) THEN
        RETURN
      ELSE
C
        option = 1000*param_int(34) + 100*param_int(64) + 10*param_int(
     +    27) + param_int(25)
        IF (option .EQ. 213) THEN
          CALL FLUROE_EULER_O3_2D_D(ndom, ithread, param_int, param_real
     +                              , ind_dm, ind_loop, ijkv_thread, 
     +                              ijkv_sdm, synchro_send_sock, 
     +                              synchro_send_th, 
     +                              synchro_receive_sock, 
     +                              synchro_receive_th, ibloc, jbloc, 
     +                              kbloc, icache, jcache, kcache, rop, 
     +                              ropd, drodm, drodmd, wig, venti, 
     +                              ventj, ventk, ti, tj, tk, vol, xmut)
C
        ELSE
          WRITE(*, *) ' option = ', option
          WRITE(*, *) 'Unknown flux options'
          CALL ERROR('gtfl3$', 70, 1)
C
        END IF
      END IF
      END
